# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_clustering_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 363)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.damagedOutliersLineEdit = QtWidgets.QLineEdit(Dialog)
        self.damagedOutliersLineEdit.setObjectName("damagedOutliersLineEdit")
        self.horizontalLayout.addWidget(self.damagedOutliersLineEdit)
        self.calculatePushButton = QtWidgets.QPushButton(Dialog)
        self.calculatePushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.calculatePushButton.setObjectName("calculatePushButton")
        self.horizontalLayout.addWidget(self.calculatePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 135))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 60, 21))
        self.label_5.setObjectName("label_5")
        self.thumbAccuracy_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbAccuracy_lineEdit.setEnabled(False)
        self.thumbAccuracy_lineEdit.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.thumbAccuracy_lineEdit.setReadOnly(True)
        self.thumbAccuracy_lineEdit.setObjectName("thumbAccuracy_lineEdit")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.label_6.setObjectName("label_6")
        self.thumbDD_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbDD_lineEdit_percents.setEnabled(False)
        self.thumbDD_lineEdit_percents.setGeometry(QtCore.QRect(160, 40, 61, 21))
        self.thumbDD_lineEdit_percents.setReadOnly(True)
        self.thumbDD_lineEdit_percents.setObjectName("thumbDD_lineEdit_percents")
        self.thumbDD_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbDD_lineEdit_number.setEnabled(False)
        self.thumbDD_lineEdit_number.setGeometry(QtCore.QRect(220, 40, 61, 21))
        self.thumbDD_lineEdit_number.setReadOnly(True)
        self.thumbDD_lineEdit_number.setObjectName("thumbDD_lineEdit_number")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label_7.setObjectName("label_7")
        self.thumbDS_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbDS_lineEdit_percents.setEnabled(False)
        self.thumbDS_lineEdit_percents.setGeometry(QtCore.QRect(160, 60, 61, 21))
        self.thumbDS_lineEdit_percents.setReadOnly(True)
        self.thumbDS_lineEdit_percents.setObjectName("thumbDS_lineEdit_percents")
        self.thumbDS_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbDS_lineEdit_number.setEnabled(False)
        self.thumbDS_lineEdit_number.setGeometry(QtCore.QRect(220, 60, 61, 21))
        self.thumbDS_lineEdit_number.setReadOnly(True)
        self.thumbDS_lineEdit_number.setObjectName("thumbDS_lineEdit_number")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 141, 21))
        self.label_9.setObjectName("label_9")
        self.thumbSS_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbSS_lineEdit_percents.setEnabled(False)
        self.thumbSS_lineEdit_percents.setGeometry(QtCore.QRect(160, 80, 61, 21))
        self.thumbSS_lineEdit_percents.setReadOnly(True)
        self.thumbSS_lineEdit_percents.setObjectName("thumbSS_lineEdit_percents")
        self.thumbSS_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbSS_lineEdit_number.setEnabled(False)
        self.thumbSS_lineEdit_number.setGeometry(QtCore.QRect(220, 80, 61, 21))
        self.thumbSS_lineEdit_number.setReadOnly(True)
        self.thumbSS_lineEdit_number.setObjectName("thumbSS_lineEdit_number")
        self.thumbSD_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbSD_lineEdit_number.setEnabled(False)
        self.thumbSD_lineEdit_number.setGeometry(QtCore.QRect(220, 100, 61, 21))
        self.thumbSD_lineEdit_number.setReadOnly(True)
        self.thumbSD_lineEdit_number.setObjectName("thumbSD_lineEdit_number")
        self.thumbSD_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_2)
        self.thumbSD_lineEdit_percents.setEnabled(False)
        self.thumbSD_lineEdit_percents.setGeometry(QtCore.QRect(160, 100, 61, 21))
        self.thumbSD_lineEdit_percents.setReadOnly(True)
        self.thumbSD_lineEdit_percents.setObjectName("thumbSD_lineEdit_percents")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 135))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 60, 21))
        self.label_15.setObjectName("label_15")
        self.eq_histAccuracy_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histAccuracy_lineEdit.setEnabled(False)
        self.eq_histAccuracy_lineEdit.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.eq_histAccuracy_lineEdit.setReadOnly(True)
        self.eq_histAccuracy_lineEdit.setObjectName("eq_histAccuracy_lineEdit")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.label_16.setObjectName("label_16")
        self.eq_histDD_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histDD_lineEdit_percents.setEnabled(False)
        self.eq_histDD_lineEdit_percents.setGeometry(QtCore.QRect(160, 40, 61, 21))
        self.eq_histDD_lineEdit_percents.setReadOnly(True)
        self.eq_histDD_lineEdit_percents.setObjectName("eq_histDD_lineEdit_percents")
        self.eq_histDD_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histDD_lineEdit_number.setEnabled(False)
        self.eq_histDD_lineEdit_number.setGeometry(QtCore.QRect(220, 40, 61, 21))
        self.eq_histDD_lineEdit_number.setReadOnly(True)
        self.eq_histDD_lineEdit_number.setObjectName("eq_histDD_lineEdit_number")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label_17.setObjectName("label_17")
        self.eq_histDS_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histDS_lineEdit_percents.setEnabled(False)
        self.eq_histDS_lineEdit_percents.setGeometry(QtCore.QRect(160, 60, 61, 21))
        self.eq_histDS_lineEdit_percents.setReadOnly(True)
        self.eq_histDS_lineEdit_percents.setObjectName("eq_histDS_lineEdit_percents")
        self.eq_histDS_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histDS_lineEdit_number.setEnabled(False)
        self.eq_histDS_lineEdit_number.setGeometry(QtCore.QRect(220, 60, 61, 21))
        self.eq_histDS_lineEdit_number.setReadOnly(True)
        self.eq_histDS_lineEdit_number.setObjectName("eq_histDS_lineEdit_number")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 100, 141, 21))
        self.label_19.setObjectName("label_19")
        self.eq_histSS_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histSS_lineEdit_percents.setEnabled(False)
        self.eq_histSS_lineEdit_percents.setGeometry(QtCore.QRect(160, 80, 61, 21))
        self.eq_histSS_lineEdit_percents.setReadOnly(True)
        self.eq_histSS_lineEdit_percents.setObjectName("eq_histSS_lineEdit_percents")
        self.eq_histSS_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histSS_lineEdit_number.setEnabled(False)
        self.eq_histSS_lineEdit_number.setGeometry(QtCore.QRect(220, 80, 61, 21))
        self.eq_histSS_lineEdit_number.setReadOnly(True)
        self.eq_histSS_lineEdit_number.setObjectName("eq_histSS_lineEdit_number")
        self.eq_histSD_lineEdit_number = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histSD_lineEdit_number.setEnabled(False)
        self.eq_histSD_lineEdit_number.setGeometry(QtCore.QRect(220, 100, 61, 21))
        self.eq_histSD_lineEdit_number.setReadOnly(True)
        self.eq_histSD_lineEdit_number.setObjectName("eq_histSD_lineEdit_number")
        self.eq_histSD_lineEdit_percents = QtWidgets.QLineEdit(self.groupBox_3)
        self.eq_histSD_lineEdit_percents.setEnabled(False)
        self.eq_histSD_lineEdit_percents.setGeometry(QtCore.QRect(160, 100, 61, 21))
        self.eq_histSD_lineEdit_percents.setReadOnly(True)
        self.eq_histSD_lineEdit_percents.setObjectName("eq_histSD_lineEdit_percents")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Damaged labels:"))
        self.calculatePushButton.setText(_translate("Dialog", "Calculate"))
        self.groupBox_2.setTitle(_translate("Dialog", "Original images"))
        self.label_5.setText(_translate("Dialog", "Accuracy"))
        self.label_6.setText(_translate("Dialog", "Damaged -> Damaged"))
        self.label_7.setText(_translate("Dialog", "Damaged -> Survived"))
        self.label_8.setText(_translate("Dialog", "Survived -> Survived"))
        self.label_9.setText(_translate("Dialog", "Survived -> Damaged"))
        self.groupBox_3.setTitle(_translate("Dialog", "High contrast images"))
        self.label_15.setText(_translate("Dialog", "Accuracy"))
        self.label_16.setText(_translate("Dialog", "Damaged -> Damaged"))
        self.label_17.setText(_translate("Dialog", "Damaged -> Survived"))
        self.label_18.setText(_translate("Dialog", "Survived -> Survived"))
        self.label_19.setText(_translate("Dialog", "Survived -> Damaged"))

