# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'object_recognition_mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 400))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(10, 10, 0, 5)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(240, 200))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(50, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.min_pts_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_pts_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.min_pts_doubleSpinBox.setSizePolicy(sizePolicy)
        self.min_pts_doubleSpinBox.setMaximumSize(QtCore.QSize(80, 25))
        self.min_pts_doubleSpinBox.setObjectName("min_pts_doubleSpinBox")
        self.gridLayout_3.addWidget(self.min_pts_doubleSpinBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(50, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 5, 0, 1, 1)
        self.radius_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radius_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.radius_doubleSpinBox.setSizePolicy(sizePolicy)
        self.radius_doubleSpinBox.setMaximumSize(QtCore.QSize(80, 25))
        self.radius_doubleSpinBox.setMaximum(111111111.0)
        self.radius_doubleSpinBox.setObjectName("radius_doubleSpinBox")
        self.gridLayout_3.addWidget(self.radius_doubleSpinBox, 0, 1, 1, 1)
        self.min_pts_doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.min_pts_doubleSpinBox2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_pts_doubleSpinBox2.sizePolicy().hasHeightForWidth())
        self.min_pts_doubleSpinBox2.setSizePolicy(sizePolicy)
        self.min_pts_doubleSpinBox2.setMaximumSize(QtCore.QSize(80, 25))
        self.min_pts_doubleSpinBox2.setObjectName("min_pts_doubleSpinBox2")
        self.gridLayout_3.addWidget(self.min_pts_doubleSpinBox2, 1, 2, 1, 1)
        self.radiusAllPictureCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.radiusAllPictureCheckBox.setObjectName("radiusAllPictureCheckBox")
        self.gridLayout_3.addWidget(self.radiusAllPictureCheckBox, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(50, 25))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.eps_horizontalSlider2 = QtWidgets.QSlider(self.groupBox)
        self.eps_horizontalSlider2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eps_horizontalSlider2.sizePolicy().hasHeightForWidth())
        self.eps_horizontalSlider2.setSizePolicy(sizePolicy)
        self.eps_horizontalSlider2.setMinimumSize(QtCore.QSize(100, 0))
        self.eps_horizontalSlider2.setMaximumSize(QtCore.QSize(160, 25))
        self.eps_horizontalSlider2.setMaximum(1000)
        self.eps_horizontalSlider2.setProperty("value", 100)
        self.eps_horizontalSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.eps_horizontalSlider2.setObjectName("eps_horizontalSlider2")
        self.gridLayout_3.addWidget(self.eps_horizontalSlider2, 7, 1, 1, 2)
        self.eps_doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.eps_doubleSpinBox2.setEnabled(False)
        self.eps_doubleSpinBox2.setMaximumSize(QtCore.QSize(60, 25))
        self.eps_doubleSpinBox2.setSingleStep(0.01)
        self.eps_doubleSpinBox2.setObjectName("eps_doubleSpinBox2")
        self.gridLayout_3.addWidget(self.eps_doubleSpinBox2, 7, 0, 1, 1)
        self.eps_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.eps_doubleSpinBox.setMaximumSize(QtCore.QSize(60, 25))
        self.eps_doubleSpinBox.setMaximum(10.0)
        self.eps_doubleSpinBox.setSingleStep(0.01)
        self.eps_doubleSpinBox.setProperty("value", 1.0)
        self.eps_doubleSpinBox.setObjectName("eps_doubleSpinBox")
        self.gridLayout_3.addWidget(self.eps_doubleSpinBox, 6, 0, 1, 1)
        self.eps_horizontalSlider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eps_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.eps_horizontalSlider.setSizePolicy(sizePolicy)
        self.eps_horizontalSlider.setMinimumSize(QtCore.QSize(160, 0))
        self.eps_horizontalSlider.setMaximumSize(QtCore.QSize(160, 25))
        self.eps_horizontalSlider.setMaximum(500)
        self.eps_horizontalSlider.setProperty("value", 100)
        self.eps_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.eps_horizontalSlider.setObjectName("eps_horizontalSlider")
        self.gridLayout_3.addWidget(self.eps_horizontalSlider, 6, 1, 1, 2)
        self.verticalLayout_7.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.points_label = QtWidgets.QLabel(self.groupBox_3)
        self.points_label.setMaximumSize(QtCore.QSize(62, 20))
        self.points_label.setObjectName("points_label")
        self.verticalLayout_8.addWidget(self.points_label)
        self.clusters_label = QtWidgets.QLabel(self.groupBox_3)
        self.clusters_label.setMaximumSize(QtCore.QSize(62, 20))
        self.clusters_label.setObjectName("clusters_label")
        self.verticalLayout_8.addWidget(self.clusters_label)
        self.clusters_label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.clusters_label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.clusters_label_2.setObjectName("clusters_label_2")
        self.verticalLayout_8.addWidget(self.clusters_label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pointsLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointsLineEdit.sizePolicy().hasHeightForWidth())
        self.pointsLineEdit.setSizePolicy(sizePolicy)
        self.pointsLineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.pointsLineEdit.setObjectName("pointsLineEdit")
        self.verticalLayout_9.addWidget(self.pointsLineEdit)
        self.clustersLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.clustersLineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.clustersLineEdit.setObjectName("clustersLineEdit")
        self.verticalLayout_9.addWidget(self.clustersLineEdit)
        self.outliersLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.outliersLineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.outliersLineEdit.setObjectName("outliersLineEdit")
        self.verticalLayout_9.addWidget(self.outliersLineEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.clustersLineEdit2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.clustersLineEdit2.setMaximumSize(QtCore.QSize(40, 20))
        self.clustersLineEdit2.setObjectName("clustersLineEdit2")
        self.verticalLayout_10.addWidget(self.clustersLineEdit2)
        self.pointsLineEdit2 = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointsLineEdit2.sizePolicy().hasHeightForWidth())
        self.pointsLineEdit2.setSizePolicy(sizePolicy)
        self.pointsLineEdit2.setMaximumSize(QtCore.QSize(40, 20))
        self.pointsLineEdit2.setObjectName("pointsLineEdit2")
        self.verticalLayout_10.addWidget(self.pointsLineEdit2)
        self.outliersLineEdit2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.outliersLineEdit2.setMaximumSize(QtCore.QSize(40, 20))
        self.outliersLineEdit2.setObjectName("outliersLineEdit2")
        self.verticalLayout_10.addWidget(self.outliersLineEdit2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.preProcessPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.preProcessPushButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.preProcessPushButton.setObjectName("preProcessPushButton")
        self.horizontalLayout_6.addWidget(self.preProcessPushButton)
        self.showClustersPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.showClustersPushButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.showClustersPushButton.setObjectName("showClustersPushButton")
        self.horizontalLayout_6.addWidget(self.showClustersPushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 10, 10, 5)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 320))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 530, 318))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelOutliersPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.labelOutliersPushButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.labelOutliersPushButton.setObjectName("labelOutliersPushButton")
        self.horizontalLayout_2.addWidget(self.labelOutliersPushButton)
        self.clustersNumberToShowSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.clustersNumberToShowSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.clustersNumberToShowSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clustersNumberToShowSpinBox.setMinimum(1)
        self.clustersNumberToShowSpinBox.setProperty("value", 5)
        self.clustersNumberToShowSpinBox.setObjectName("clustersNumberToShowSpinBox")
        self.horizontalLayout_2.addWidget(self.clustersNumberToShowSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.mergeClustersPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.mergeClustersPushButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.mergeClustersPushButton.setObjectName("mergeClustersPushButton")
        self.horizontalLayout_2.addWidget(self.mergeClustersPushButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Clustering parameters"))
        self.label_3.setText(_translate("MainWindow", "Min_pts"))
        self.label_2.setText(_translate("MainWindow", "Eps"))
        self.radiusAllPictureCheckBox.setText(_translate("MainWindow", "All picture"))
        self.label.setText(_translate("MainWindow", "Radius"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Clustering info: Original | High contrast"))
        self.points_label.setText(_translate("MainWindow", "Points #"))
        self.clusters_label.setText(_translate("MainWindow", "Clusters #"))
        self.clusters_label_2.setText(_translate("MainWindow", "Outliers #"))
        self.preProcessPushButton.setText(_translate("MainWindow", "Pre-process"))
        self.showClustersPushButton.setText(_translate("MainWindow", "Show clusters"))
        self.labelOutliersPushButton.setText(_translate("MainWindow", "Label Outliers"))
        self.mergeClustersPushButton.setText(_translate("MainWindow", "Merge clusters"))

