# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 773)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(950, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(270, 360))
        self.tabWidget.setMaximumSize(QtCore.QSize(270, 360))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 260, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 320))
        self.groupBox.setMaximumSize(QtCore.QSize(260, 320))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.thresholdingLabel = QtWidgets.QLabel(self.groupBox)
        self.thresholdingLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.thresholdingLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.thresholdingLabel.setFont(font)
        self.thresholdingLabel.setObjectName("thresholdingLabel")
        self.gridLayout_2.addWidget(self.thresholdingLabel, 5, 0, 1, 1)
        self.thresholdingComboBox = QtWidgets.QComboBox(self.groupBox)
        self.thresholdingComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.thresholdingComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.thresholdingComboBox.setObjectName("thresholdingComboBox")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.thresholdingComboBox.addItem("")
        self.gridLayout_2.addWidget(self.thresholdingComboBox, 5, 1, 1, 1)
        self.plotObjectsCheckBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plotObjectsCheckBox.setFont(font)
        self.plotObjectsCheckBox.setObjectName("plotObjectsCheckBox")
        self.gridLayout_2.addWidget(self.plotObjectsCheckBox, 9, 0, 1, 1)
        self.noise2FilterLabel = QtWidgets.QLabel(self.groupBox)
        self.noise2FilterLabel.setObjectName("noise2FilterLabel")
        self.gridLayout_2.addWidget(self.noise2FilterLabel, 4, 0, 1, 1)
        self.dimensionsLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dimensionsLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.dimensionsLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dimensionsLineEdit.setReadOnly(True)
        self.dimensionsLineEdit.setObjectName("dimensionsLineEdit")
        self.gridLayout_2.addWidget(self.dimensionsLineEdit, 0, 1, 1, 1)
        self.fillingHolesComboBox = QtWidgets.QComboBox(self.groupBox)
        self.fillingHolesComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.fillingHolesComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fillingHolesComboBox.setObjectName("fillingHolesComboBox")
        self.fillingHolesComboBox.addItem("")
        self.fillingHolesComboBox.addItem("")
        self.gridLayout_2.addWidget(self.fillingHolesComboBox, 7, 1, 1, 1)
        self.noiseFilterLabel = QtWidgets.QLabel(self.groupBox)
        self.noiseFilterLabel.setObjectName("noiseFilterLabel")
        self.gridLayout_2.addWidget(self.noiseFilterLabel, 2, 0, 1, 1)
        self.edgeFilterLabel = QtWidgets.QLabel(self.groupBox)
        self.edgeFilterLabel.setObjectName("edgeFilterLabel")
        self.gridLayout_2.addWidget(self.edgeFilterLabel, 3, 0, 1, 1)
        self.fillHolesLabel = QtWidgets.QLabel(self.groupBox)
        self.fillHolesLabel.setObjectName("fillHolesLabel")
        self.gridLayout_2.addWidget(self.fillHolesLabel, 7, 0, 1, 1)
        self.edgeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.edgeComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.edgeComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edgeComboBox.setObjectName("edgeComboBox")
        self.edgeComboBox.addItem("")
        self.edgeComboBox.addItem("")
        self.edgeComboBox.addItem("")
        self.edgeComboBox.addItem("")
        self.edgeComboBox.addItem("")
        self.gridLayout_2.addWidget(self.edgeComboBox, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 13, 1, 1, 1)
        self.channelComboBox = QtWidgets.QComboBox(self.groupBox)
        self.channelComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.channelComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.channelComboBox.setObjectName("channelComboBox")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.channelComboBox.addItem("")
        self.gridLayout_2.addWidget(self.channelComboBox, 1, 1, 1, 1)
        self.noiseComboBox = QtWidgets.QComboBox(self.groupBox)
        self.noiseComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.noiseComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.noiseComboBox.setObjectName("noiseComboBox")
        self.noiseComboBox.addItem("")
        self.noiseComboBox.addItem("")
        self.noiseComboBox.addItem("")
        self.noiseComboBox.addItem("")
        self.gridLayout_2.addWidget(self.noiseComboBox, 2, 1, 1, 1)
        self.noise2ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.noise2ComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.noise2ComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.noise2ComboBox.setObjectName("noise2ComboBox")
        self.noise2ComboBox.addItem("")
        self.noise2ComboBox.addItem("")
        self.noise2ComboBox.addItem("")
        self.noise2ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.noise2ComboBox, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.binClosingComboBox = QtWidgets.QComboBox(self.groupBox)
        self.binClosingComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.binClosingComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.binClosingComboBox.setObjectName("binClosingComboBox")
        self.binClosingComboBox.addItem("")
        self.binClosingComboBox.addItem("")
        self.gridLayout_2.addWidget(self.binClosingComboBox, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 13, 2, 1, 1)
        self.binClosingLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.binClosingLabel.setFont(font)
        self.binClosingLabel.setObjectName("binClosingLabel")
        self.gridLayout_2.addWidget(self.binClosingLabel, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 13, 0, 1, 1)
        self.dimensionsLabel = QtWidgets.QLabel(self.groupBox)
        self.dimensionsLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.dimensionsLabel.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dimensionsLabel.setFont(font)
        self.dimensionsLabel.setObjectName("dimensionsLabel")
        self.gridLayout_2.addWidget(self.dimensionsLabel, 0, 0, 1, 1)
        self.channelLabel = QtWidgets.QLabel(self.groupBox)
        self.channelLabel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.channelLabel.setObjectName("channelLabel")
        self.gridLayout_2.addWidget(self.channelLabel, 1, 0, 1, 1)
        self.plotFiltersCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.plotFiltersCheckBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plotFiltersCheckBox.setFont(font)
        self.plotFiltersCheckBox.setObjectName("plotFiltersCheckBox")
        self.gridLayout_2.addWidget(self.plotFiltersCheckBox, 9, 1, 1, 1)
        self.minRegionSpinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.minRegionSpinbox.setMaximum(100000.0)
        self.minRegionSpinbox.setObjectName("minRegionSpinbox")
        self.gridLayout_2.addWidget(self.minRegionSpinbox, 0, 2, 1, 1)
        self.noiseSpinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.noiseSpinbox.setMaximum(100000.0)
        self.noiseSpinbox.setObjectName("noiseSpinbox")
        self.gridLayout_2.addWidget(self.noiseSpinbox, 2, 2, 1, 1)
        self.edgeSpinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.edgeSpinbox.setMaximum(100000.0)
        self.edgeSpinbox.setObjectName("edgeSpinbox")
        self.gridLayout_2.addWidget(self.edgeSpinbox, 3, 2, 1, 1)
        self.noise2Spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.noise2Spinbox.setMaximum(100000.0)
        self.noise2Spinbox.setObjectName("noise2Spinbox")
        self.gridLayout_2.addWidget(self.noise2Spinbox, 4, 2, 1, 1)
        self.thresholding_minSpinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.thresholding_minSpinbox.setMaximum(100000.0)
        self.thresholding_minSpinbox.setObjectName("thresholding_minSpinbox")
        self.gridLayout_2.addWidget(self.thresholding_minSpinbox, 5, 2, 1, 1)
        self.bin_closingSpinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.bin_closingSpinbox.setMaximum(100000.0)
        self.bin_closingSpinbox.setObjectName("bin_closingSpinbox")
        self.gridLayout_2.addWidget(self.bin_closingSpinbox, 6, 2, 1, 1)
        self.useOriginalCheckBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.useOriginalCheckBox.setFont(font)
        self.useOriginalCheckBox.setObjectName("useOriginalCheckBox")
        self.gridLayout_2.addWidget(self.useOriginalCheckBox, 9, 2, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 260, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(260, 320))
        self.groupBox_2.setMaximumSize(QtCore.QSize(260, 320))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plotObjectsCheckBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plotObjectsCheckBox_3.setFont(font)
        self.plotObjectsCheckBox_3.setObjectName("plotObjectsCheckBox_3")
        self.gridLayout_3.addWidget(self.plotObjectsCheckBox_3, 9, 0, 1, 1)
        self.plotFiltersCheckBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.plotFiltersCheckBox_3.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plotFiltersCheckBox_3.setFont(font)
        self.plotFiltersCheckBox_3.setObjectName("plotFiltersCheckBox_3")
        self.gridLayout_3.addWidget(self.plotFiltersCheckBox_3, 9, 1, 1, 1)
        self.dimensionsLineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.dimensionsLineEdit_2.setMinimumSize(QtCore.QSize(80, 0))
        self.dimensionsLineEdit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dimensionsLineEdit_2.setReadOnly(True)
        self.dimensionsLineEdit_2.setObjectName("dimensionsLineEdit_2")
        self.gridLayout_3.addWidget(self.dimensionsLineEdit_2, 0, 1, 1, 1)
        self.edgeComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.edgeComboBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.edgeComboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edgeComboBox_2.setObjectName("edgeComboBox_2")
        self.edgeComboBox_2.addItem("")
        self.edgeComboBox_2.addItem("")
        self.edgeComboBox_2.addItem("")
        self.edgeComboBox_2.addItem("")
        self.edgeComboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.edgeComboBox_2, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 12, 0, 1, 1)
        self.dimensionsLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.dimensionsLabel_2.setMinimumSize(QtCore.QSize(100, 0))
        self.dimensionsLabel_2.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dimensionsLabel_2.setFont(font)
        self.dimensionsLabel_2.setObjectName("dimensionsLabel_2")
        self.gridLayout_3.addWidget(self.dimensionsLabel_2, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 12, 2, 1, 1)
        self.binClosingComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.binClosingComboBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.binClosingComboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.binClosingComboBox_2.setObjectName("binClosingComboBox_2")
        self.binClosingComboBox_2.addItem("")
        self.binClosingComboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.binClosingComboBox_2, 6, 1, 1, 1)
        self.fillHolesLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.fillHolesLabel_2.setObjectName("fillHolesLabel_2")
        self.gridLayout_3.addWidget(self.fillHolesLabel_2, 7, 0, 1, 1)
        self.noise2FilterLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.noise2FilterLabel_2.setObjectName("noise2FilterLabel_2")
        self.gridLayout_3.addWidget(self.noise2FilterLabel_2, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 12, 1, 1, 1)
        self.thresholdingLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.thresholdingLabel_2.setMinimumSize(QtCore.QSize(120, 0))
        self.thresholdingLabel_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.thresholdingLabel_2.setFont(font)
        self.thresholdingLabel_2.setObjectName("thresholdingLabel_2")
        self.gridLayout_3.addWidget(self.thresholdingLabel_2, 5, 0, 1, 1)
        self.fillingHolesComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.fillingHolesComboBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.fillingHolesComboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fillingHolesComboBox_2.setObjectName("fillingHolesComboBox_2")
        self.fillingHolesComboBox_2.addItem("")
        self.fillingHolesComboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.fillingHolesComboBox_2, 7, 1, 1, 1)
        self.noiseFilterLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.noiseFilterLabel_2.setObjectName("noiseFilterLabel_2")
        self.gridLayout_3.addWidget(self.noiseFilterLabel_2, 2, 0, 1, 1)
        self.edgeFilterLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.edgeFilterLabel_2.setObjectName("edgeFilterLabel_2")
        self.gridLayout_3.addWidget(self.edgeFilterLabel_2, 3, 0, 1, 1)
        self.binClosingLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.binClosingLabel_2.setFont(font)
        self.binClosingLabel_2.setObjectName("binClosingLabel_2")
        self.gridLayout_3.addWidget(self.binClosingLabel_2, 6, 0, 1, 1)
        self.noise2ComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.noise2ComboBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.noise2ComboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.noise2ComboBox_2.setObjectName("noise2ComboBox_2")
        self.noise2ComboBox_2.addItem("")
        self.noise2ComboBox_2.addItem("")
        self.noise2ComboBox_2.addItem("")
        self.noise2ComboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.noise2ComboBox_2, 4, 1, 1, 1)
        self.channelComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.channelComboBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.channelComboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.channelComboBox_2.setObjectName("channelComboBox_2")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.channelComboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.channelComboBox_2, 1, 1, 1, 1)
        self.channelLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.channelLabel_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.channelLabel_2.setObjectName("channelLabel_2")
        self.gridLayout_3.addWidget(self.channelLabel_2, 1, 0, 1, 1)
        self.noiseComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.noiseComboBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.noiseComboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.noiseComboBox_2.setObjectName("noiseComboBox_2")
        self.noiseComboBox_2.addItem("")
        self.noiseComboBox_2.addItem("")
        self.noiseComboBox_2.addItem("")
        self.noiseComboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.noiseComboBox_2, 2, 1, 1, 1)
        self.thresholdingComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.thresholdingComboBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.thresholdingComboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.thresholdingComboBox_2.setObjectName("thresholdingComboBox_2")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.thresholdingComboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.thresholdingComboBox_2, 5, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 8, 0, 1, 1)
        self.minRegionSpinbox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.minRegionSpinbox_2.setMaximum(100000.0)
        self.minRegionSpinbox_2.setObjectName("minRegionSpinbox_2")
        self.gridLayout_3.addWidget(self.minRegionSpinbox_2, 0, 2, 1, 1)
        self.noiseSpinbox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.noiseSpinbox_2.setMaximum(100000.0)
        self.noiseSpinbox_2.setObjectName("noiseSpinbox_2")
        self.gridLayout_3.addWidget(self.noiseSpinbox_2, 2, 2, 1, 1)
        self.edgeSpinbox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.edgeSpinbox_2.setMaximum(100000.0)
        self.edgeSpinbox_2.setObjectName("edgeSpinbox_2")
        self.gridLayout_3.addWidget(self.edgeSpinbox_2, 3, 2, 1, 1)
        self.noise2Spinbox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.noise2Spinbox_2.setMaximum(100000.0)
        self.noise2Spinbox_2.setObjectName("noise2Spinbox_2")
        self.gridLayout_3.addWidget(self.noise2Spinbox_2, 4, 2, 1, 1)
        self.thresholding_minSpinbox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.thresholding_minSpinbox_2.setMaximum(100000.0)
        self.thresholding_minSpinbox_2.setObjectName("thresholding_minSpinbox_2")
        self.gridLayout_3.addWidget(self.thresholding_minSpinbox_2, 5, 2, 1, 1)
        self.bin_closingSpinbox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.bin_closingSpinbox_2.setMaximum(100000.0)
        self.bin_closingSpinbox_2.setObjectName("bin_closingSpinbox_2")
        self.gridLayout_3.addWidget(self.bin_closingSpinbox_2, 6, 2, 1, 1)
        self.useContrastCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.useContrastCheckBox.setFont(font)
        self.useContrastCheckBox.setObjectName("useContrastCheckBox")
        self.gridLayout_3.addWidget(self.useContrastCheckBox, 9, 2, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(270, 55))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 55))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cpuCoresSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.cpuCoresSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.cpuCoresSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cpuCoresSpinBox.setObjectName("cpuCoresSpinBox")
        self.horizontalLayout.addWidget(self.cpuCoresSpinBox)
        self.selectAllCpuCorescheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.selectAllCpuCorescheckBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.selectAllCpuCorescheckBox.setObjectName("selectAllCpuCorescheckBox")
        self.horizontalLayout.addWidget(self.selectAllCpuCorescheckBox)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.image3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.image3.setMinimumSize(QtCore.QSize(400, 0))
        self.image3.setObjectName("image3")
        self.horizontalLayout_7.addWidget(self.image3)
        self.image4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.image4.setMinimumSize(QtCore.QSize(400, 0))
        self.image4.setObjectName("image4")
        self.horizontalLayout_7.addWidget(self.image4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.image2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.image2.setMinimumSize(QtCore.QSize(400, 0))
        self.image2.setObjectName("image2")
        self.horizontalLayout_3.addWidget(self.image2)
        self.image = QtWidgets.QGraphicsView(self.centralwidget)
        self.image.setMinimumSize(QtCore.QSize(400, 0))
        self.image.setObjectName("image")
        self.horizontalLayout_3.addWidget(self.image)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.runInitializationButton = QtWidgets.QToolButton(self.centralwidget)
        self.runInitializationButton.setMinimumSize(QtCore.QSize(100, 0))
        self.runInitializationButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.runInitializationButton.setObjectName("runInitializationButton")
        self.horizontalLayout_5.addWidget(self.runInitializationButton)
        self.runObjectsButton = QtWidgets.QToolButton(self.centralwidget)
        self.runObjectsButton.setMinimumSize(QtCore.QSize(90, 0))
        self.runObjectsButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.runObjectsButton.setObjectName("runObjectsButton")
        self.horizontalLayout_5.addWidget(self.runObjectsButton)
        self.stopButton = QtWidgets.QToolButton(self.centralwidget)
        self.stopButton.setMinimumSize(QtCore.QSize(90, 0))
        self.stopButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_5.addWidget(self.stopButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.imageNumSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageNumSpinbox.sizePolicy().hasHeightForWidth())
        self.imageNumSpinbox.setSizePolicy(sizePolicy)
        self.imageNumSpinbox.setMinimumSize(QtCore.QSize(90, 0))
        self.imageNumSpinbox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.imageNumSpinbox.setMaximum(1000)
        self.imageNumSpinbox.setObjectName("imageNumSpinbox")
        self.horizontalLayout_4.addWidget(self.imageNumSpinbox)
        self.imageNumHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.imageNumHorizontalSlider.setMinimumSize(QtCore.QSize(300, 0))
        self.imageNumHorizontalSlider.setMaximumSize(QtCore.QSize(300, 16777215))
        self.imageNumHorizontalSlider.setMaximum(1000)
        self.imageNumHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageNumHorizontalSlider.setObjectName("imageNumHorizontalSlider")
        self.horizontalLayout_4.addWidget(self.imageNumHorizontalSlider)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelect_photos_folder = QtWidgets.QAction(MainWindow)
        self.actionSelect_photos_folder.setObjectName("actionSelect_photos_folder")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Filters parameters"))
        self.thresholdingLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">Thresholding</span></p></body></html>"))
        self.thresholdingComboBox.setItemText(0, _translate("MainWindow", "Otsu <"))
        self.thresholdingComboBox.setItemText(1, _translate("MainWindow", "Otsu >"))
        self.thresholdingComboBox.setItemText(2, _translate("MainWindow", "Yen <"))
        self.thresholdingComboBox.setItemText(3, _translate("MainWindow", "Yen >"))
        self.thresholdingComboBox.setItemText(4, _translate("MainWindow", "Manual <"))
        self.thresholdingComboBox.setItemText(5, _translate("MainWindow", "Manual >"))
        self.thresholdingComboBox.setItemText(6, _translate("MainWindow", "Mean <"))
        self.thresholdingComboBox.setItemText(7, _translate("MainWindow", "Mean >"))
        self.thresholdingComboBox.setItemText(8, _translate("MainWindow", "Minimum <"))
        self.thresholdingComboBox.setItemText(9, _translate("MainWindow", "Minimum >"))
        self.thresholdingComboBox.setItemText(10, _translate("MainWindow", "None"))
        self.plotObjectsCheckBox.setText(_translate("MainWindow", "Plot objects"))
        self.noise2FilterLabel.setText(_translate("MainWindow", "Noise filter"))
        self.fillingHolesComboBox.setItemText(0, _translate("MainWindow", "Fill holes"))
        self.fillingHolesComboBox.setItemText(1, _translate("MainWindow", "None"))
        self.noiseFilterLabel.setText(_translate("MainWindow", "Noise filter"))
        self.edgeFilterLabel.setText(_translate("MainWindow", "Edge filter"))
        self.fillHolesLabel.setText(_translate("MainWindow", "Fill holes"))
        self.edgeComboBox.setItemText(0, _translate("MainWindow", "Sobel"))
        self.edgeComboBox.setItemText(1, _translate("MainWindow", "Canny"))
        self.edgeComboBox.setItemText(2, _translate("MainWindow", "Entropy"))
        self.edgeComboBox.setItemText(3, _translate("MainWindow", "Background"))
        self.edgeComboBox.setItemText(4, _translate("MainWindow", "None"))
        self.channelComboBox.setItemText(0, _translate("MainWindow", "RGB R"))
        self.channelComboBox.setItemText(1, _translate("MainWindow", "RGB G"))
        self.channelComboBox.setItemText(2, _translate("MainWindow", "RGB B"))
        self.channelComboBox.setItemText(3, _translate("MainWindow", "HSV H"))
        self.channelComboBox.setItemText(4, _translate("MainWindow", "HSV S"))
        self.channelComboBox.setItemText(5, _translate("MainWindow", "HSV V"))
        self.channelComboBox.setItemText(6, _translate("MainWindow", "Gray eye"))
        self.channelComboBox.setItemText(7, _translate("MainWindow", "Gray equal"))
        self.channelComboBox.setItemText(8, _translate("MainWindow", "Normalised"))
        self.channelComboBox.setItemText(9, _translate("MainWindow", "Original"))
        self.noiseComboBox.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.noiseComboBox.setItemText(1, _translate("MainWindow", "Median"))
        self.noiseComboBox.setItemText(2, _translate("MainWindow", "Mean"))
        self.noiseComboBox.setItemText(3, _translate("MainWindow", "None"))
        self.noise2ComboBox.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.noise2ComboBox.setItemText(1, _translate("MainWindow", "Median"))
        self.noise2ComboBox.setItemText(2, _translate("MainWindow", "Mean"))
        self.noise2ComboBox.setItemText(3, _translate("MainWindow", "None"))
        self.binClosingComboBox.setItemText(0, _translate("MainWindow", "Closing"))
        self.binClosingComboBox.setItemText(1, _translate("MainWindow", "None"))
        self.binClosingLabel.setText(_translate("MainWindow", "Binary closing"))
        self.dimensionsLabel.setText(_translate("MainWindow", "Dimensions/Min."))
        self.channelLabel.setText(_translate("MainWindow", "Channel"))
        self.plotFiltersCheckBox.setText(_translate("MainWindow", "Plot filters"))
        self.useOriginalCheckBox.setText(_translate("MainWindow", "Use Original"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Original"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filters parameters"))
        self.plotObjectsCheckBox_3.setText(_translate("MainWindow", "Plot objects"))
        self.plotFiltersCheckBox_3.setText(_translate("MainWindow", "Plot filters"))
        self.edgeComboBox_2.setItemText(0, _translate("MainWindow", "Sobel"))
        self.edgeComboBox_2.setItemText(1, _translate("MainWindow", "Canny"))
        self.edgeComboBox_2.setItemText(2, _translate("MainWindow", "Entropy"))
        self.edgeComboBox_2.setItemText(3, _translate("MainWindow", "Background"))
        self.edgeComboBox_2.setItemText(4, _translate("MainWindow", "None"))
        self.dimensionsLabel_2.setText(_translate("MainWindow", "Dimensions/Min. "))
        self.binClosingComboBox_2.setItemText(0, _translate("MainWindow", "Closing"))
        self.binClosingComboBox_2.setItemText(1, _translate("MainWindow", "None"))
        self.fillHolesLabel_2.setText(_translate("MainWindow", "Fill holes"))
        self.noise2FilterLabel_2.setText(_translate("MainWindow", "Noise filter"))
        self.thresholdingLabel_2.setText(_translate("MainWindow", "<html><head/><body><p>Thresholding</p></body></html>"))
        self.fillingHolesComboBox_2.setItemText(0, _translate("MainWindow", "Fill holes"))
        self.fillingHolesComboBox_2.setItemText(1, _translate("MainWindow", "None"))
        self.noiseFilterLabel_2.setText(_translate("MainWindow", "Noise filter"))
        self.edgeFilterLabel_2.setText(_translate("MainWindow", "Edge filter"))
        self.binClosingLabel_2.setText(_translate("MainWindow", "Binary closing"))
        self.noise2ComboBox_2.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.noise2ComboBox_2.setItemText(1, _translate("MainWindow", "Median"))
        self.noise2ComboBox_2.setItemText(2, _translate("MainWindow", "Mean"))
        self.noise2ComboBox_2.setItemText(3, _translate("MainWindow", "None"))
        self.channelComboBox_2.setItemText(0, _translate("MainWindow", "RGB R"))
        self.channelComboBox_2.setItemText(1, _translate("MainWindow", "RGB G"))
        self.channelComboBox_2.setItemText(2, _translate("MainWindow", "RGB B"))
        self.channelComboBox_2.setItemText(3, _translate("MainWindow", "HSV H"))
        self.channelComboBox_2.setItemText(4, _translate("MainWindow", "HSV S"))
        self.channelComboBox_2.setItemText(5, _translate("MainWindow", "HSV V"))
        self.channelComboBox_2.setItemText(6, _translate("MainWindow", "Gray eye"))
        self.channelComboBox_2.setItemText(7, _translate("MainWindow", "Gray equal"))
        self.channelComboBox_2.setItemText(8, _translate("MainWindow", "Normalised"))
        self.channelComboBox_2.setItemText(9, _translate("MainWindow", "Original"))
        self.channelLabel_2.setText(_translate("MainWindow", "Channel"))
        self.noiseComboBox_2.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.noiseComboBox_2.setItemText(1, _translate("MainWindow", "Median"))
        self.noiseComboBox_2.setItemText(2, _translate("MainWindow", "Mean"))
        self.noiseComboBox_2.setItemText(3, _translate("MainWindow", "None"))
        self.thresholdingComboBox_2.setItemText(0, _translate("MainWindow", "Otsu <"))
        self.thresholdingComboBox_2.setItemText(1, _translate("MainWindow", "Otsu >"))
        self.thresholdingComboBox_2.setItemText(2, _translate("MainWindow", "Yen <"))
        self.thresholdingComboBox_2.setItemText(3, _translate("MainWindow", "Yen >"))
        self.thresholdingComboBox_2.setItemText(4, _translate("MainWindow", "Manual <"))
        self.thresholdingComboBox_2.setItemText(5, _translate("MainWindow", "Manual >"))
        self.thresholdingComboBox_2.setItemText(6, _translate("MainWindow", "Mean <"))
        self.thresholdingComboBox_2.setItemText(7, _translate("MainWindow", "Mean >"))
        self.thresholdingComboBox_2.setItemText(8, _translate("MainWindow", "Minimum <"))
        self.thresholdingComboBox_2.setItemText(9, _translate("MainWindow", "Minimum >"))
        self.thresholdingComboBox_2.setItemText(10, _translate("MainWindow", "None"))
        self.useContrastCheckBox.setText(_translate("MainWindow", "Use Contrast"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "High contrast"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Computer parameters"))
        self.label.setText(_translate("MainWindow", "CPU cores:"))
        self.selectAllCpuCorescheckBox.setText(_translate("MainWindow", "Select all"))
        self.runInitializationButton.setText(_translate("MainWindow", "Process single"))
        self.runObjectsButton.setText(_translate("MainWindow", "Process all"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.actionSelect_photos_folder.setText(_translate("MainWindow", "Select photos folder..."))

